export const housesDataSource = [
{
    "id": 1,
    "favorite": true,
    "address": "Ponte Avonwick, 652",
    "city": "Toronto",
    "state": "ON",
    "zipcode": "89050-230",
    "beds": 4,
    "baths": 4,
    "housesize": 7500,
    "lotsize": 0.8,
    "price": 780000,
    "coordinates": "43.7507639, -79.3184378",
    "features": "Lavadora de louças, Disposição, Lavanderia separada, 3/4 de banho no térreo, Sala de jantar formal, Sala de família, Sala de estar separada, Café da manhã / balcão, copa (copa), bancadas de granito na cozinha, piso de madeira na cozinha, cozinha console, bancadas de superfície sólida na cozinha, foyer de entrada, sala de estar da frente, ventilador de teto no quarto principal, quarto principal separado do outro, armário da porta espelhada no quarto principal, 2 quartos: 11x13, 3 quartos: 11x14, 4 Quarto: 18x13, Alarme Propriedade do sistema, Microondas embutido, Carpete, Ventilador (es) de teto, Forno de convecção, Dupla embutida em fornos a gás, Fogão a gás, Fogão a gás, Piso de mármore / pedra",
    "yearbuilt": 2008,
    "type": 0,
    "status": 1,
    "image": "images/gallery/1.jpg",
    "agentid": 1,
    "agent": {
    "id": 1,
    "name": "Gustavo Oliveira",
    "phone": "(21) 3555-9392",
    "picture": "images/employees/01.png"
    }
},
{
    "id": 2,
    "favorite": true,
    "address": "Rua Topeka, 826",
    "city": "Riverbank",
    "state": "CA",
    "zipcode": "95360-010",
    "beds": 5,
    "baths": 3,
    "housesize": 12500,
    "lotsize": 1.2,
    "price": 1750000,
    "coordinates": "37.7369999,-120.9430488",
    "features": "Lavadora de louças, Disposição, Lavanderia separada, Banheiro completo no térreo, Sala de jantar formal, Sala de família, Sala de estar separada, Café da manhã / balcão, copa (copa), bancadas de granito na cozinha, armários personalizados de cozinha, ilha de cozinha , Despensa, Hall de entrada, Sala de estar formal, Sala de estar de trás, Tecto abobadado na sala de estar, Varanda no quarto principal, Quarto principal separado dos outros, Quarto principal no andar de cima, Sala no quarto principal, Closet no mestre quarto, 2 quartos: 13X20, 3 quartos: 13X17, 4 Quarto: 13X18, 5 Quarto: 14X16, sistema de alarme de propriedade, Persianas, Built-in forno elétrico, Built-in microondas, Carpete, ventilador de teto (s), Fogão a gás, Sistema de intercomunicação, Piso de mármore / pedra, Condicionador de água próprio, Sistema de filtragem de água, Coberturas de janela por toda parte",
    "yearbuilt": 2009,
    "type": 0,
    "status": 0,
    "image": "images/gallery/2.jpg",
    "agentid": 2,
    "agent": {
    "id": 2,
    "name": "Viviane Pereira",
    "phone": "(31) 3555-2728",
    "picture": "images/employees/09.png"
    }
},
{
    "id": 3,
    "favorite": false,
    "address": "Avenida S Kerema, 328",
    "city": "Milford",
    "state": "CT",
    "zipcode": "06465-150",
    "beds": 4,
    "baths": 2,
    "housesize": 8356,
    "lotsize": 0.04,
    "price": 350000,
    "coordinates": "41.1957999,-73.1022988",
    "features": "Máquina de lavar louças, Eliminação, Frigorífico, Lavandaria separada, Lavadora / Secadora no 2º andar, Casa de banho completa no térreo, Sala de jantar formal, Sala de família, Sala de estar separada, Sala de pequeno-almoço cozinha, bancadas em granito na cozinha, ilha de cozinha, mármore / revestimento de pedra na cozinha, despensa, sala de estar formal, sala de estar da frente, quarto principal separado do outro, quarto principal no andar superior, sala de estar no quarto principal, closet no quarto principal , 2º quarto: 16x12, 3º quarto: 13x16, 4º quarto: 18x12, sistema de alarme, forno embutido, carpete, ventilador (s) de teto, forno elétrico embutido duplo, fogão a gás, piso de mármore / pedra",
    "yearbuilt": 2010,
    "type": 0,
    "status": 0,
    "image": "images/gallery/3.jpg",
    "agentid": 3,
    "agent": {
    "id": 3,
    "name": "Humberto Lopes",
    "phone": "(81) 8555-2387",
    "picture": "images/employees/03.png"
    }
},
{
    "id": 4,
    "favorite": false,
    "address": "Rua Beryl, 5119",
    "city": "San Antonio",
    "state": "TX",
    "zipcode": "78212-000",
    "beds": 4,
    "baths": 2,
    "housesize": 7980,
    "lotsize": 0.7,
    "price": 455000,
    "coordinates": "29.4972699,-98.5366788",
    "features": "Lavadora de louças, Disposição, Geladeira, Lavanderia separada, Banheiro completo no térreo, Sala de estar / sala de jantar, Quarto para família separado, Café da manhã / balcão, copa (copa), Bancadas de granito na cozinha, Armários personalizados de cozinha, Cozinha ilha, Recesso iluminação na cozinha, piso de cerâmica na cozinha, despensa, sala de estar formal, sala de estar da frente, ventilador de teto no quarto principal, quarto principal no térreo, Walk-in closet no quarto principal, 2 quartos: 15x13, 3 quartos: 12x12, Quarto: 14x12, Sistema de alarme, Estores, Microondas embutido, Carpete, Ventilador (es) de teto, Aspiração central, Forno da convecção, Fornos eléctricos duplos integrados, Cooktop eléctrico, Intercomunicador, Pisos",
    "yearbuilt": 2007,
    "type": 0,
    "status": 1,
    "image": "images/gallery/4.jpg",
    "agentid": 4,
    "agent": {
    "id": 4,
    "name": "Eliane Ribeiro",
    "phone": "(81) 8555-6546",
    "picture": "images/employees/04.png"
    }
},
{
    "id": 5,
    "favorite": true,
    "address": "Salto Norte, 6120",
    "city": "Moorhead",
    "state": "MN",
    "zipcode": "56564-900",
    "beds": 5,
    "baths": 4,
    "housesize": 14250,
    "lotsize": 1.1,
    "price": 1700000,
    "coordinates": "46.88933,-96.7522388",
    "features": "Lavadora de louças, Disposição, Lavanderia separada, Lavadora / Secadora no 1 ° andar, Banheiro completo no andar inferior, Sala de jantar formal, Sala de família, Sala de estar independente, Café da manhã / balcão, copa Armários personalizados, Ilha de cozinha, Sala de estar formal, Sala de estar traseira, Sala de estar submersa, Tecto abobadado na sala de estar, Varanda no quarto principal, Ventilador de teto no quarto principal, Quarto principal separado do outro, Quarto principal no andar superior, Walk-in closet quarto principal, 2º quarto: 16X17, 3º quarto: 14X16, 4º quarto: 13X13, 5º quarto: 12X12, estores, micro-ondas embutido, Carpete, Ventilador (s) de teto, Aspiração central, Fornos elétricos internos duplos, Fogão a gás , Pisos de mármore / pedra, prateleiras de panela, condicionador de água de propriedade, sistema de filtragem de água, coberturas de janela em todo",
    "yearbuilt": 2010,
    "type": 0,
    "status": 0,
    "image": "images/gallery/5.jpg",
    "agentid": 1,
    "agent": {
    "id": 1,
    "name": "Gustavo Oliveira",
    "phone": "(21) 3555-9392",
    "picture": "images/employees/01.png"
    }
},
{
    "id": 6,
    "favorite": false,
    "address": "Alameda Tanglewood, 8512",
    "city": "Reform",
    "state": "AL",
    "zipcode": "35487-500",
    "beds": 3,
    "baths": 2,
    "housesize": 5600,
    "lotsize": 0.2,
    "price": 250000,
    "coordinates": "33.3794,-87.9785788",
    "features": "Máquina de lavar louça, eliminação, geladeira, lavanderia separada, banho completo no térreo, sala de jantar formal, estantes embutidas na sala de família, sala de família baixo, sala de estar separada, Breakfast Bar / balcão, copa (área), bancadas em granito cozinha, armários personalizados de cozinha, ilha de cozinha, mármore / revestimento de pedra na cozinha, despensa, sala de estar formal, frente sala de estar, ventilador de teto no quarto principal, quarto principal no térreo, quarto principal separado do outro, sala de estar no quarto principal, Walk- closet no quarto principal, 2 quartos: 11X15, 3 quartos: 11X14, sistema de alarme de propriedade, persianas, built-in microondas, carpete, ventilador de teto (s), duplo built-in fornos elétricos, cortinas, fogão elétrico, mármore / pedra pisos, Coberturas de janela ao longo, refrigerador de vinho",
    "yearbuilt": 2011,
    "type": 0,
    "status": 0,
    "image": "images/gallery/6.jpg",
    "agentid": 2,
    "agent": {
    "id": 2,
    "name": "Viviane Pereira",
    "phone": "(31) 3555-2728",
    "picture": "images/employees/09.png"
    }
},
{
    "id": 7,
    "favorite": false,
    "address": "San Bailey, 7121",
    "city": "Worcester",
    "state": "MA",
    "zipcode": "01605-880",
    "beds": 4,
    "baths": 3,
    "housesize": 6900,
    "lotsize": 2.1,
    "price": 555000,
    "coordinates": "42.2797,-71.8746388",
    "features": "Máquina de lavar louças, Eliminação, Frigorífico, Lavandaria separada, Máquina de lavar / secar roupa no 1 ° andar, Casa de banho completa, Sala de jantar formal, Sala íntima, Sala de estar independente, Bar / Balcão, Pequeno-almoço\" iluminação na cozinha, Bancadas de azulejos na cozinha, Despensa, Entrada foyer, Sala de estar formal, Frente sala de estar, Camarim no quarto principal, Mestre quarto separado do outro, Mestre quarto no andar de cima, Walk-in closet no quarto principal, 2 quarto: 14x16, 3º quarto: 12x13, 4º quarto: 13x14, Carpete, Fornos elétricos embutidos duplos, Drywall, Fogão a gás, Madeira artificial ou pisos laminados, Piso em mármore / pedra, Condicionador de água loope",
    "yearbuilt": 2008,
    "type": 0,
    "status": 1,
    "image": "images/gallery/7.jpg",
    "agentid": 3,
    "agent": {
    "id": 3,
    "name": "Humberto Lopes",
    "phone": "(81) 8555-2387",
    "picture": "images/employees/03.png"
    }
},
{
    "id": 8,
    "favorite": false,
    "address": "Rodovia Plymouth, 620201",
    "city": "Detroit",
    "state": "MI",
    "zipcode": "48224-440",
    "beds": 4,
    "baths": 4,
    "housesize": 7840,
    "lotsize": 0.33,
    "price": 610000,
    "coordinates": "42.3716299,-83.2572188",
    "features": "Máquina de lavar louças, Eliminação, Frigorífico, Lavandaria separada, Casa de banho completa no térreo, Sala de jantar formal, 2+ quartos familiares, Sala de estar separada, copa (copa), Bancadas de granito na cozinha, Armários personalizados de cozinha, Cozinha ilha, Walk-in despensa, hall de entrada, sala de estar formal, sala de estar traseiro, teto abobadado na sala de estar, ventilador de teto no quarto principal, quarto principal no térreo, Walk-in closet no quarto principal, 2 quartos: 12x15, 3 quartos: 12x15, 4 Quarto: 12x15, Gavetas, Microondas embutido, Carpete, Ventilador (es) de teto, Fogão eléctrico, Persianas, Clarabóia (s), Sistema de filtragem de água, Revestimento de janela parcia",
    "yearbuilt": 2010,
    "type": 0,
    "status": 0,
    "image": "images/gallery/8.jpg",
    "agentid": 4,
    "agent": {
    "id": 4,
    "name": "Eliane Ribeiro",
    "phone": "(81) 8555-6546",
    "picture": "images/employees/04.png"
    }
},
{
    "id": 9,
    "favorite": false,
    "address": "Rua Theresa, 1198",
    "city": "Whitinsville",
    "state": "MA",
    "zipcode": "01582-280",
    "beds": 4,
    "baths": 3,
    "housesize": 4990,
    "lotsize": 0.8,
    "price": 320000,
    "coordinates": "42.1072,-71.6928888",
    "features": "Máquina de lavar louça, eliminação, geladeira, lavanderia separada, lavadora / secadora no 1 º andar, 1/2 banho no térreo, sala de jantar formal, 2 + quartos familiares, estantes embutidas na sala de família, café da manhã Bar / balcão, bancadas em granito na cozinha , Ilha de cozinha, Pavimento em mosaico na cozinha, Despensa, Hall de entrada, Sala de estar formal, Estantes embutidas no quarto principal, Centro de entretenimento embutido no quarto principal, Ventilador de teto no quarto principal, Camarim no quarto principal, Walk-in closet no quarto principal, 2 quartos: 13x12, 3 quartos: 12x12, 4 quartos: 13x12, sistema de alarme alugado, persianas, built-in microondas, carpete, ventilador de teto (s), duplo fornos a gás embutidos, telha pisos, coberturas de janela em todo",
    "yearbuilt": 2011,
    "type": 0,
    "status": 0,
    "image": "images/gallery/9.jpg",
    "agentid": 1,
    "agent": {
    "id": 1,
    "name": "Gustavo Oliveira",
    "phone": "(21) 3555-9392",
    "picture": "images/employees/01.png"
    }
}];
